name: Vanilla

main: com.niccholaspage.Vanilla.Vanilla

version: 0.2-SNAPSHOT

commands:
  vanilla:
    usage: /<command>
    description: Allows you to view Vanilla version and reload the configuration