name: Vanilla

main: com.niccholaspage.Vanilla.Vanilla

version: 0.2

commands:
  vanilla:
    usage: /<command>
    description: Allows you to view Vanilla version and reload the configuration
    
permissions:
  Vanilla.version:
    description: Allows you to check Vanilla's version
  Vanilla.reload:
    description: Allows you to reload Vanilla's configuration
  Vanilla.default.plugins:
    description: Shows the default /plugins command
  Vanilla.default.version:
    description: Shows the default /version command